apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-liveness
  namespace: level1
  labels:
    app: liveness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-demo
  template:
    metadata:
      labels:
        app: liveness-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        
        # HTTP liveness probe
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3

---
# Test liveness probe:
# 1. Apply this deployment
# 2. Wait for pod to be running
# 3. Delete the index file to make probe fail:
#    kubectl exec -it <pod-name> -- rm /usr/share/nginx/html/index.html
# 4. Watch pod restart:
#    kubectl get pods -w
# 5. After 3 failures (15s), pod restarts automatically
