apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-ready-app
  namespace: level1
  labels:
    app: prod-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        # Resource management
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        
        # Startup probe - gives app time to initialize
        # Disables liveness probe until app is started
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30    # Allow 150 seconds (30 * 5s)
        
        # Liveness probe - restarts container if unhealthy
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3     # Fail after 30s (3 * 10s)
        
        # Readiness probe - removes from service if not ready
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3     # Not ready after 15s (3 * 5s)

---
# This is a production-ready deployment with:
# ✅ Startup probe - protects slow-starting apps
# ✅ Liveness probe - automatic restart on failure
# ✅ Readiness probe - traffic routing control
# ✅ Resource requests - guaranteed resources
# ✅ Resource limits - prevent resource hogging
# ✅ 3 replicas - high availability

# Deploy:
# kubectl apply -f production-ready.yaml

# Verify probes:
# kubectl describe pod -l app=prod-app | grep -E "Liveness|Readiness|Startup"

# Verify resources:
# kubectl describe pod -l app=prod-app | grep -A5 Requests

# Test self-healing:
# kubectl delete pod <pod-name>
# kubectl get pods -w

# Create service:
# kubectl expose deployment production-ready-app --port=80

# Test readiness:
# kubectl exec <pod-name> -- nginx -s stop
# kubectl get endpoints production-ready-app
