apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-readiness
  namespace: level1
  labels:
    app: readiness-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness-demo
  template:
    metadata:
      labels:
        app: readiness-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        
        # TCP readiness probe
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3

---
# Test readiness probe:
# 1. Apply deployment
# 2. Create service:
#    kubectl expose deployment app-with-readiness --port=80
# 3. Check endpoints (should show 2 pod IPs):
#    kubectl get endpoints app-with-readiness
# 4. Stop nginx in one pod:
#    kubectl exec <pod-name> -- nginx -s stop
# 5. Check endpoints again (should show only 1 pod IP):
#    kubectl get endpoints app-with-readiness
# 6. Pod status shows 0/1 READY but still Running
