// ========================================
// LEVEL 3: User Service
// Learning: API calls with authentication, data fetching
// ========================================

import api from "./api";

/**
 * Get all users from the database
 * Note: In production, this would be paginated
 *
 * @returns {Promise<Array>} Array of user objects
 */
export const getAllUsers = async () => {
  try {
    // Using our api instance (has interceptors)
    const response = await api.get("/users");

    // Transform data to add role field
    const users = response.map((user) => ({
      ...user,
      role: user.user_role || "STUDENT", // Default to STUDENT if null
    }));

    return users;
  } catch (error) {
    console.error("Get users error:", error);
    throw new Error("Failed to fetch users");
  }
};

/**
 * Get a single user by ID
 *
 * @param {number} userId - User ID
 * @returns {Promise<Object>} User object
 */
export const getUserById = async (userId) => {
  try {
    const response = await api.get(`/users/${userId}`);

    // Transform data to add role field
    return {
      ...response,
      role: response.user_role || "STUDENT",
    };
  } catch (error) {
    console.error("Get user error:", error);
    throw new Error("Failed to fetch user");
  }
};

/**
 * Update user profile
 *
 * @param {number} userId - User ID
 * @param {Object} data - Updated user data
 * @returns {Promise<Object>} Updated user object
 */
export const updateUser = async (userId, data) => {
  try {
    const response = await api.put(`/users/${userId}`, data);

    // Transform data to add role field
    return {
      ...response,
      role: response.user_role || "STUDENT",
    };
  } catch (error) {
    console.error("Update user error:", error);
    throw new Error("Failed to update user");
  }
};

/*
🎓 LEARNING NOTES:

1. API INSTANCE:
   - Uses the api instance from api.js
   - Automatically includes auth token
   - Interceptors handle errors globally

2. HTTP METHODS:
   - GET: Retrieve data
   - POST: Create new data
   - PUT: Update existing data
   - DELETE: Remove data

3. STRAPI ENDPOINTS:
   - /users - Get all users (requires auth)
   - /users/:id - Get/update specific user
   - Auto-generated by Strapi

4. ERROR PROPAGATION:
   - catch block logs error
   - throw new Error() passes to caller
   - Component handles final error display

5. ASYNC FUNCTIONS:
   - Always return Promise
   - Use await to call
   - Handle errors with try/catch
*/
