apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: level2
  labels:
    app: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        
        # Load environment variables from Secret
        envFrom:
        - secretRef:
            name: postgres-secret
        
        # Resource management
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Persistent volume mount
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres  # IMPORTANT: Prevents "data directory not empty" errors
        
        # Readiness probe - checks if database is ready for connections
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Liveness probe - checks if database is alive
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      
      # Volume reference
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data

---
# StatefulSet vs Deployment:
# ✅ Stable pod names (postgres-0, postgres-1, ...)
# ✅ Ordered creation/deletion
# ✅ Persistent storage per pod
# ✅ Stable network identity

# Deploy:
# kubectl apply -f postgres-statefulset.yaml

# Check status:
# kubectl get statefulset postgres -n level2
# kubectl get pods -n level2

# Check logs:
# kubectl logs postgres-0 -n level2

# Connect to database:
# kubectl exec -it postgres-0 -n level2 -- psql -U templeadmin -d templedb

# Test connection:
# kubectl exec -it postgres-0 -n level2 -- pg_isready -U templeadmin -d templedb
