apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: level1
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Optional: auto-assigned if omitted (30000-32767)
