apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
  
  - name: sidecar
    image: busybox:1.35
    command: ['sh', '-c', 'while true; do echo "$(date): Hello from sidecar" >> /var/log/sidecar.log; sleep 30; done']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  
  volumes:
  - name: shared-logs
    emptyDir: {}
