apiVersion: v1
kind: Service
metadata:
  name: temple-api-service
  namespace: level2
  labels:
    app: temple-api
spec:
  type: ClusterIP
  selector:
    app: temple-api
  ports:
  - name: http
    port: 1337
    targetPort: 1337
    protocol: TCP
  sessionAffinity: None

---
# ClusterIP service - accessible only within the cluster
# DNS names:
# - temple-api-service (within level2 namespace)
# - temple-api-service.level2.svc.cluster.local (FQDN)

# Check service:
# kubectl get svc temple-api-service -n level2

# Check endpoints (should show 2 pod IPs):
# kubectl get endpoints temple-api-service -n level2

# Test from within cluster:
# kubectl run curl --image=curlimages/curl --rm -it -n level2 -- \
#   curl http://temple-api-service:1337/_health

# Port-forward for local testing:
# kubectl port-forward svc/temple-api-service -n level2 1337:1337
# curl http://localhost:1337/_health
# open http://localhost:1337/admin
