apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-hook
  annotations:
    # Run before sync
    argocd.argoproj.io/hook: PreSync
    
    # Delete hook after completion
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
    # Run in wave 0 (before app resources)
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 2
  template:
    metadata:
      name: db-migration
    spec:
      restartPolicy: Never
      
      containers:
      - name: migrate
        image: temple-api:latest
        command:
        - sh
        - -c
        - |
          echo "Running database migrations..."
          npm run migrate
          echo "Migrations complete!"
        
        env:
        - name: DATABASE_HOST
          value: postgres-service
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

---
# This job runs BEFORE the application syncs
# Use cases:
# - Database schema migrations
# - Data seeding
# - Pre-deployment validation
# - Backup before update

# Other hook types:
# - PostSync: Run after successful sync
# - SyncFail: Run when sync fails
# - Skip: Don't deploy this resource
