// src/setupTests.js – executed before all vitest tests
// Provide the runtime env object that the app expects
// In production this file is generated by env.sh, but in tests we mock it.
window._env_ = {
    VITE_API_URL: "http://dev.els-api.local/api"
};
