apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: level2
  labels:
    app: temple-ui
data:
  # React environment variables (injected at build time)
  REACT_APP_API_URL: "http://localhost:1337"
  REACT_APP_ENV: "production"
  REACT_APP_TITLE: "Temple Management System"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temple-ui
  namespace: level2
  labels:
    app: temple-ui
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temple-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: temple-ui
        tier: frontend
    spec:
      containers:
      - name: ui
        image: temple-ui:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: temple-ui-service
  namespace: level2
  labels:
    app: temple-ui
spec:
  type: LoadBalancer
  selector:
    app: temple-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---
# Access:
# kubectl get svc temple-ui-service -n level2
# open http://localhost (Docker Desktop LoadBalancer)
